modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="realm_of_salum"
version="1.0.0"
displayName="Realm of Salum"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="User, MCreator"

[[dependencies.realm_of_salum]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




